name: Build and Deploy Docker Image

on:
  push:
    branches:
      - new  # Trigger the workflow only on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image with a versioned tag
    - name: Build Docker image
      run: |
        docker build -t aadhitya369/dbapi:latest -t aadhitya369/dbapi:v1.0.0 .

    # Step 4: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push aadhitya369/dbapi:latest
        docker push aadhitya369/dbapi:v1.0.0